#!/usr/bin/env node
/* The launch pack's stylesheets, scoped into src/ as real files.
 *
 * docs/launch/code/NN-*.css  ->  src/.../ref-*.css
 *
 * START-HERE: "add the reference stylesheet to the repo as a real file and
 * import it — never retype the rules, never adjust a value, never map them
 * onto existing components." Both halves are honoured here, and the one thing
 * that cannot be is recorded rather than fudged.
 *
 * THE SHEETS STYLE BARE CLASS NAMES. `.card`, `.tab`, `.search`, `.pill`,
 * `.box`, `.av`, `.chap`, `.sub` — every one of them already paints something
 * else in this app, and `01-tokens-and-base.css` opens with `*{box-sizing}`
 * and a `button{...}` reset, which unscoped is not a collision but the whole
 * app. check:collisions exists in this repo because that has shipped before.
 *
 * So NOTHING is renamed and NO value is touched. Every selector gets the
 * bundle's root class in front of it, and the sheet simply cannot escape its
 * screen. The class names in the reference markup are produced exactly as
 * written, which is what lets the JSX be copied from it.
 *
 * WHAT IS CUT, AND WHY — each one named, so "verbatim" stays checkable:
 *   · the :root token blocks. The reference was written against THIS app's
 *     vocabulary — --ground, --panel, --raised, --line, --t1/2/3, --copilot,
 *     --ok — and its dark values ARE the app's Sky night livery, to the
 *     decimal. Keeping them would pin every student to one livery. The nine
 *     tokens the app does not emit are aliased below, which is the only new
 *     CSS here and is adaptation, not layout.
 *   · the global reset: *, html, body, button, :focus-visible. A scoped `*`
 *     is still every element on the screen and would restyle the app bar
 *     through it.
 *
 * Generated, not hand-edited, so the two cannot drift:
 *   npm run ref:css
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const MARK = "C";

/* Cuts, by name. `find` is what comes out; `guard` is what must then be gone
   — if the guard still matches, the shape changed and this refuses rather
   than silently shipping a global reset. */
const CUTS = [
  { why: "the :root token block (the app's livery engine emits these)",
    find: /:root\{[\s\S]*?\n\}\n/g, guard: /:root\{/ },
  { why: "the dark-scheme token block",
    find: /@media \(prefers-color-scheme:dark\)\{:root[\s\S]*?\n\}\}\n/g, guard: /prefers-color-scheme:dark\)\{:root/ },
  { why: "the [data-theme=dark] token block",
    find: /:root\[data-theme="dark"\]\{[\s\S]*?\n\}\n/g, guard: /:root\[data-theme="dark"\]\{/ },
  { why: "the global reset — *, html, body, button, :focus-visible",
    find: /\*\{box-sizing:border-box\}\nhtml,body\{[^}]*\}\nbody\{[^}]*\}\nbutton\{[^}]*\}\nbutton:focus-visible[^}]*\}\n/g,
    guard: /^\*\{box-sizing/m },
];

const BUNDLES = [
  { root: ".ref-mod", out: "src/components/module/ref-module.css",
    src: ["01-tokens-and-base.css", "11-module-screen.css"] },
  { root: ".ref-les", out: "src/components/module/ref-lesson.css",
    src: ["01-tokens-and-base.css", "12-lesson-page.css"] },
  { root: ".ref-lic", out: "src/components/licence/ref-licence.css",
    src: ["01-tokens-and-base.css", "02-licence-card.css", "03-stamp-creator.css",
          "04-account-and-preferences.css"] },
];

/* The nine the app does not emit. Values are the reference's own where it has
   one, and the app's token where the app has the same idea under another
   name. This is the adaptation layer — the only lines here that are not the
   reference's, and they set no layout. */
const VARS = `/* GENERATED by scripts/scope-ref-css.mjs — do not edit. */
ROOT{
  /* The app's accent, under the reference's name. */
  --accent: var(--active);
  --accent-soft: color-mix(in oklab, var(--active) 14%, transparent);
  /* The reference's hairline is its --line at 55%; the app emits only --line. */
  --hair: color-mix(in srgb, var(--line) 58%, transparent);
  /* Faces are reached through tokens and never named (CLAUDE.md). */
  --sans: var(--font-ui);
  --mono: var(--font-mono);
  /* The reference's own literals for the ones it defines outright. */
  --r: 13px;
  --wrap: 1010px;
  --video: oklch(.16 .02 255);
  --glow: none;
}
`;

function scopeOne(bundle) {
  let source = bundle.src
    .map((f) => readFileSync(join(ROOT, "docs/launch/code", f), "utf8"))
    .join("\n");
  const cut = [];
  for (const c of CUTS) {
    c.find.lastIndex = 0;
    if (c.find.test(source)) {
      c.find.lastIndex = 0;
      source = source.replace(c.find, "\n");
      cut.push(c.why);
    }
    if (c.guard.test(source)) {
      console.error(`REFUSING (${bundle.out}): ${c.why} — still there in a shape this does not recognise.`);
      process.exit(1);
    }
  }

  /* Comments out first, back in last: a comma inside prose was being read as
     a selector separator and the prefix landed mid-sentence. */
  const comments = [];
  const masked = source.replace(/\/\*[\s\S]*?\*\//g, (m) => {
    comments.push(m);
    return `${MARK}${comments.length - 1}__`;
  });

  const scopeSelector = (sel) => sel.split(",").map((one) => {
    const bare = one.replace(new RegExp(`${MARK}\\d+__`, "g"), "").trim();
    if (!bare) return one;
    if (bare.startsWith(bundle.root)) return one;
    if (/^(from|to|[\d.]+%)$/.test(bare)) return one;   // a keyframe step
    if (bare.startsWith("@")) return one;               // an at-rule prelude
    let at = 0;
    const re = new RegExp(`${MARK}\\d+__`, "g");
    let m;
    while ((m = re.exec(one)) !== null) at = m.index + m[0].length;
    while (at < one.length && /\s/.test(one[at])) at += 1;
    return `${one.slice(0, at)}${bundle.root} ${one.slice(at)}`;
  }).join(",");

  let out = "";
  let buffer = "";
  let depth = 0;
  let inAt = 0;
  for (const ch of masked) {
    if (ch === "{") {
      const prelude = buffer.trim();
      /* Inside @media / @supports the next prelude is a selector again; inside
         @keyframes it is a step and must not be touched. */
      if (depth === 0 && /@(media|supports|container)/.test(prelude)) {
        out += `${buffer}{`; inAt = 1;
      } else if (depth === 0 && /@keyframes/.test(prelude)) {
        out += `${buffer}{`; inAt = -1;
      } else if (inAt === -1 && depth === 1) {
        out += `${buffer}{`;
      } else {
        out += `${scopeSelector(buffer)}{`;
      }
      buffer = ""; depth += 1;
    } else if (ch === "}") {
      out += `${buffer}}`; buffer = ""; depth -= 1;
      if (depth === 0) inAt = 0;
    } else buffer += ch;
  }
  out += buffer;

  const text = out.replace(new RegExp(`${MARK}(\\d+)__`, "g"), (_, i) => comments[+i]);
  const head = `/* GENERATED by scripts/scope-ref-css.mjs from ${bundle.src.join(" + ")}.
   DO NOT EDIT. Every selector is prefixed with ${bundle.root} so the sheet
   cannot escape its screen; nothing is renamed and no value is changed.
   Cut on the way in:
${cut.map((c) => `     . ${c}`).join("\n")}
   Re-generate with: npm run ref:css */
`;

  writeFileSync(join(ROOT, bundle.out),
    head + VARS.replace("ROOT", bundle.root) + text.replace(/\n{3,}/g, "\n\n"));
  console.log(`wrote ${bundle.out}  (${text.split("\n").length} lines, ${cut.length} cuts)`);
}

for (const b of BUNDLES) scopeOne(b);
