-- Wingman — discovery: how a student who knows nobody reaches somebody
--
-- Run after 0010. Safe to re-run. Adds columns to two existing tables, creates
-- two tables and a set of functions. Alters no existing column and drops
-- nothing.
--
-- ===========================================================================
-- THE BOUNDARY LIVES HERE, NOT IN THE CLIENT
-- ===========================================================================
-- Read the header of 0009 first; the same architecture applies and for the
-- same reason. auth.uid() is NULL on every request, every table carries
-- `using (true)`, and the browser holds the anon key. So a rule expressed only
-- as "the UI does not call that endpoint" is not a rule — PostgREST will serve
-- the table to anyone who asks.
--
-- The rule this file has to hold is §3 of the brief: a person may appear in
-- search only if the searcher already shares a squadron with them, or that
-- person has answered in a module the searcher studies. Some of these students
-- are under 18. An app where an adult can search a minor by name is a grooming
-- vector, and "the client happens not to send that query" is not a defence.
--
-- So people_search is a function that cannot return a stranger whatever it is
-- asked for. It is not authentication — passing another user's id returns
-- THEIR orbit, which is a lateral move, the same trade 0009 documents — it is
-- one statement of the rule in the place the rule applies, so a second caller
-- cannot quietly disagree with the first.
-- ===========================================================================

-- ------------------------------------------------------------- 1 · squadrons
-- The table from 0005 has no name, which is why every squadron in the client
-- is currently identified by its module code. Discovery needs a room to be a
-- named thing you can be told about.
alter table squadrons add column if not exists name         text;
alter table squadrons add column if not exists blurb        text;
alter table squadrons add column if not exists owner_id     text;
alter table squadrons add column if not exists exam_window  text;

-- open        anyone may join immediately
-- request     joining creates a row in squadron_join_requests
-- invite_only the default, and the only way in is a link or an invite
alter table squadrons add column if not exists join_policy  text not null default 'invite_only';
do $$ begin
  alter table squadrons add constraint squadrons_join_policy_known
    check (join_policy in ('open', 'request', 'invite_only'));
exception when duplicate_object then null; end $$;

-- PER SQUADRON, NOT GLOBAL. 32 is a full class of 28 plus a repeat student, a
-- late joiner and an instructor. Open rooms are left NULL — uncapped — because
-- a cohort room that fills up locks out exactly the newcomers it exists for.
-- The brief flags this number as the one open decision; it is a default on a
-- column, so changing it is one statement rather than a migration of logic.
alter table squadrons add column if not exists member_cap   integer default 32;

-- The shareable link. One per squadron, regenerated by revoking.
alter table squadrons add column if not exists invite_token       text;
alter table squadrons add column if not exists invite_expires_at  timestamptz;
alter table squadrons add column if not exists invite_revoked_at  timestamptz;
create unique index if not exists squadrons_invite_token_idx
  on squadrons (lower(invite_token)) where invite_token is not null;

-- ------------------------------------------------------------- 2 · profiles
-- SET BY THE STUDENT, NEVER INFERRED. The brief is explicit: exam window and
-- active window are things a person says about themselves. Current module,
-- answer habit and study rhythm are derived below and deliberately not stored,
-- so they cannot drift from the behaviour they describe.
alter table pilot_profiles add column if not exists exam_window   text;
alter table pilot_profiles add column if not exists active_window text;   -- morning|afternoon|evening|night
alter table pilot_profiles add column if not exists timezone      text;
-- The opt-out. Removes a student from people-search entirely and leaves every
-- squadron they are already in untouched.
alter table pilot_profiles add column if not exists discoverable  boolean not null default true;

-- --------------------------------------------------------- 3 · new tables
-- A request is not a join. §8: nothing auto-joins anyone to anything, and an
-- invite cannot force-add — it is a request the invited person accepts.
create table if not exists squadron_join_requests (
  squadron_id uuid        not null references squadrons (id) on delete cascade,
  user_id     text        not null,
  state       text        not null default 'pending' check (state in ('pending','accepted','declined')),
  created_at  timestamptz not null default now(),
  decided_at  timestamptz,
  primary key (squadron_id, user_id)
);
create index if not exists squadron_join_requests_user_idx on squadron_join_requests (user_id, state);

-- Person-to-person, as distinct from the squadron's shareable link above.
-- "Invite to a squadron" on a profile writes one of these.
create table if not exists squadron_invites (
  id           uuid        primary key default gen_random_uuid(),
  squadron_id  uuid        not null references squadrons (id) on delete cascade,
  inviter_id   text        not null,
  invitee_id   text        not null,
  state        text        not null default 'pending' check (state in ('pending','accepted','declined','revoked')),
  created_at   timestamptz not null default now(),
  unique (squadron_id, invitee_id)
);
create index if not exists squadron_invites_invitee_idx on squadron_invites (invitee_id, state);

-- NO user_blocks TABLE. The brief lists one; `blocks` already exists from 0005
-- with exactly that shape and is already read by right_seat in 0009. A second
-- block list would be two owners of one fact, and the failure mode is the bad
-- one: a person blocked in one table and not the other is visible on whichever
-- surface reads the emptier list.

do $$
declare t text;
begin
  foreach t in array array['squadron_join_requests', 'squadron_invites'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists %I on %I', t || '_open', t);
    execute format('create policy %I on %I for all using (true) with check (true)', t || '_open', t);
  end loop;
end $$;

-- --------------------------------------------------------- 4 · the orbit
-- Modules an account actually studies. There is no enrollments table in this
-- database — CLAUDE.md says there is, and it is wrong — so this is built from
-- the two signals that do exist: a chapter you completed, or a thread you
-- posted. Both are activity in the module rather than a claim about it.
create or replace function my_modules(p_me text)
returns setof text
language sql
stable
as $$
  select module_code from chapter_completions where user_id = p_me
  union
  select module_id   from lesson_threads      where author_id = p_me;
$$;

-- THE ORBIT ITSELF, and every people-facing function below goes through it.
-- True when p_me may see p_them at all: a shared squadron, or p_them has
-- written in a module p_me studies.
create or replace function in_my_orbit(p_me text, p_them text)
returns boolean
language sql
stable
as $$
  select p_me is not null and p_them is not null and p_me <> p_them and (
    exists (
      select 1 from squadron_members a
      join squadron_members b on b.squadron_id = a.squadron_id
      where a.user_id = p_me and b.user_id = p_them
    )
    or exists (
      select 1 from lesson_threads t
      where t.author_id = p_them and t.module_id in (select my_modules(p_me))
    )
    or exists (
      select 1 from lesson_replies r
      join lesson_threads t on t.id = r.thread_id
      where r.author_id = p_them and t.module_id in (select my_modules(p_me))
    )
  );
$$;

-- ------------------------------------------------------ 5 · people search
-- The only way the client is allowed to look a person up. Scoped by orbit,
-- filtered by the opt-out, and blocked BOTH WAYS — blocking is symmetric and
-- total, so neither party appears to the other, on any surface.
create or replace function people_search(p_me text, p_q text)
returns table (user_id text, callsign text, module_code text, shares_squadron boolean)
language sql
stable
as $$
  select
    p.user_id,
    p.callsign,
    (select c.module_code from chapter_completions c
      where c.user_id = p.user_id order by c.completed_at desc limit 1) as module_code,
    exists (
      select 1 from squadron_members a
      join squadron_members b on b.squadron_id = a.squadron_id
      where a.user_id = p_me and b.user_id = p.user_id
    ) as shares_squadron
  from pilot_profiles p
  where p.discoverable
    and in_my_orbit(p_me, p.user_id)
    and not exists (select 1 from blocks b
                    where (b.user_id = p_me and b.blocked_id = p.user_id)
                       or (b.user_id = p.user_id and b.blocked_id = p_me))
    and coalesce(btrim(p_q), '') <> ''
    and p.callsign ilike '%' || btrim(p_q) || '%'
  order by shares_squadron desc, p.callsign
  limit 20;
$$;

-- --------------------------------------------------------- 6 · capacity
-- Headcount is its own function because three things below need it, and a
-- copied count(*) is a rule with three owners.
create or replace function squadron_headcount(p_squadron uuid)
returns integer
language sql
stable
as $$
  select count(*)::int from squadron_members where squadron_id = p_squadron;
$$;

-- Full only when a cap is actually set. NULL member_cap means uncapped, which
-- is what open cohort rooms use.
create or replace function squadron_is_full(p_squadron uuid)
returns boolean
language sql
stable
as $$
  select s.member_cap is not null and squadron_headcount(s.id) >= s.member_cap
  from squadrons s where s.id = p_squadron;
$$;

-- ------------------------------------------------------- 7 · discovery list
-- Rooms p_me could join, SORTED BY ACTIVITY RATHER THAN SIZE — a busy room of
-- nine beats a dead room of forty. `known` is the social-proof line: people
-- already in there that p_me has studied alongside.
--
-- Capacity is returned as a headcount and a boolean, never as a fraction. §2:
-- a group of eight is a squadron; rendered as "8 of 32" it becomes a
-- half-empty one, and that framing is what kills small groups.
create or replace function discover_squadrons(p_me text, p_filter text default 'all')
returns table (
  id uuid, name text, blurb text, module_code text, exam_window text,
  join_policy text, members integer, active_week integer, is_full boolean,
  known_ids text[], already_in boolean, requested boolean
)
language sql
stable
as $$
  with mine as (select squadron_id from squadron_members where user_id = p_me),
  active as (
    select m.squadron_id, count(distinct pr.user_id)::int as n
    from squadron_members m
    left join presence pr
      on pr.user_id = m.user_id and pr.last_seen > now() - interval '7 days'
    group by m.squadron_id
  )
  select
    s.id, s.name, s.blurb, s.module_code, s.exam_window, s.join_policy,
    squadron_headcount(s.id) as members,
    coalesce(a.n, 0) as active_week,
    coalesce(squadron_is_full(s.id), false) as is_full,
    coalesce((
      select array_agg(sm.user_id)
      from squadron_members sm
      where sm.squadron_id = s.id and in_my_orbit(p_me, sm.user_id)
    ), '{}') as known_ids,
    s.id in (select squadron_id from mine) as already_in,
    exists (select 1 from squadron_join_requests r
            where r.squadron_id = s.id and r.user_id = p_me and r.state = 'pending') as requested
  from squadrons s
  left join active a on a.squadron_id = s.id
  where s.join_policy in ('open', 'request')
    and (p_filter <> 'yours' or s.module_code in (select my_modules(p_me)))
    and (p_filter <> 'exam'  or s.exam_window is not distinct from
         (select pp.exam_window from pilot_profiles pp where pp.user_id = p_me))
  order by coalesce(a.n, 0) desc, squadron_headcount(s.id) desc
  limit 40;
$$;

-- ------------------------------------------------------------- 8 · joining
-- ONE DOOR. Every route in — the discovery card, the invite link, an accepted
-- person-to-person invite — comes through here, so the capacity rule and the
-- block rule cannot be true on one path and forgotten on another.
--
-- Returns the outcome as text rather than raising: the caller renders it, and
-- "full" is an ordinary answer rather than an error.
create or replace function join_squadron(p_me text, p_squadron uuid)
returns text
language plpgsql
volatile
as $$
declare s squadrons%rowtype;
begin
  select * into s from squadrons where id = p_squadron;
  if not found then return 'missing'; end if;
  if exists (select 1 from squadron_members where squadron_id = s.id and user_id = p_me)
    then return 'already_in'; end if;
  -- A blocked person cannot arrive by any route, including a link they were
  -- given before the block.
  if exists (
    select 1 from squadron_members m
    join blocks b on (b.user_id = p_me and b.blocked_id = m.user_id)
                  or (b.user_id = m.user_id and b.blocked_id = p_me)
    where m.squadron_id = s.id
  ) then return 'unavailable'; end if;
  if coalesce(squadron_is_full(s.id), false) then return 'full'; end if;

  if s.join_policy = 'open' then
    insert into squadron_members (squadron_id, user_id) values (s.id, p_me)
      on conflict do nothing;
    return 'joined';
  elsif s.join_policy = 'request' then
    insert into squadron_join_requests (squadron_id, user_id) values (s.id, p_me)
      on conflict (squadron_id, user_id) do update set state = 'pending', decided_at = null;
    return 'requested';
  else
    return 'invite_only';
  end if;
end $$;

-- --------------------------------------------------------- 9 · invite links
-- Resolving a link is a read that already knows every reason it might fail, so
-- the page can say which one. A revoked or expired token is 'missing' on
-- purpose: a link that says "this was revoked" tells a stranger the room
-- exists.
create or replace function squadron_by_invite(p_me text, p_token text)
returns table (id uuid, name text, blurb text, members integer, state text)
language sql
stable
as $$
  select s.id, s.name, s.blurb, squadron_headcount(s.id) as members,
    case
      when s.invite_revoked_at is not null then 'missing'
      when s.invite_expires_at is not null and s.invite_expires_at < now() then 'missing'
      when exists (select 1 from squadron_members m where m.squadron_id = s.id and m.user_id = p_me)
        then 'already_in'
      when exists (
        select 1 from squadron_members m
        join blocks b on (b.user_id = p_me and b.blocked_id = m.user_id)
                      or (b.user_id = m.user_id and b.blocked_id = p_me)
        where m.squadron_id = s.id
      ) then 'unavailable'
      when coalesce(squadron_is_full(s.id), false) then 'full'
      else 'ok'
    end as state
  from squadrons s
  where lower(s.invite_token) = lower(btrim(p_token));
$$;
