-- 0013 — retire the pilot livery.
--
-- WHAT THIS REMOVES, AND WHY IT IS NOT THE LIVERY YOU ARE THINKING OF.
--
-- Two different things in this codebase were called a livery, and they had
-- nothing to do with each other beyond the word:
--
--   1. The APP's livery — sky / amber / tarmac / beacon / runway / skydrol.
--      Chosen in Profile -> Appearance, written to documentElement as
--      data-livery, and generated by src/lib/liveryEngine.js. This one is
--      current, it is the design system, and 0013 does not touch it.
--
--   2. The PILOT's livery — dawn-patrol / night-ops / contrail / carrier-deck
--      / altimeter / aurora. Picked once during signup, stored here, and used
--      to tint a person's tail. This is the older build's, and it is what 0013
--      removes.
--
-- It had already stopped meaning anything. Every --tail-<id> token in app.css
-- resolved to var(--active) for all twelve ids in both sets, under a comment
-- reading "A person carries no colour of their own under this system" — so the
-- choice painted nothing, on any screen, for anybody. What was left of it was a
-- step in onboarding asking a new student to pick between six swatches that all
-- produce the same colour, before they had seen the product.
--
-- Live values at the time of writing: 3 profiles across 2 distinct liveries,
-- 1 squadron. No information is lost, because none of it was ever rendered.
--
-- Order matters. squadron_roster is language sql and so has a hard catalogue
-- dependency on pilot_profiles.livery: the column cannot be dropped while the
-- function still selects it. Both functions are replaced first, then the
-- columns go.

-- ---------------------------------------------------------------- functions

-- Body copied from the live definition (pg_get_functiondef), with the livery
-- column removed from the one insert that set it. Nothing else changed.
create or replace function assign_squadron(uid text, mod text, stime text)
returns uuid
language plpgsql
as $$
declare target uuid;
begin
  select s.id into target
    from squadron_members m join squadrons s on s.id = m.squadron_id
   where m.user_id = uid and s.module_code = mod
   limit 1;
  if target is not null then return target; end if;

  select s.id into target from squadrons s
   where s.module_code = mod and s.study_time is not distinct from stime
     and (select count(*) from squadron_members m where m.squadron_id = s.id) < 20
   order by (select count(*) from squadron_members m where m.squadron_id = s.id) desc
   limit 1;

  if target is null then
    select s.id into target from squadrons s
     where s.module_code = mod
       and (select count(*) from squadron_members m where m.squadron_id = s.id) < 20
     order by (select count(*) from squadron_members m where m.squadron_id = s.id) desc
     limit 1;
  end if;

  if target is null then
    select s.id into target from squadrons s
     where s.study_time is not distinct from stime
       and (select count(*) from squadron_members m where m.squadron_id = s.id) < 20
     order by (select count(*) from squadron_members m where m.squadron_id = s.id) desc
     limit 1;
  end if;

  if target is null then
    select s.id into target from squadrons s
     where (select count(*) from squadron_members m where m.squadron_id = s.id) < 20
     order by (select count(*) from squadron_members m where m.squadron_id = s.id) desc
     limit 1;
  end if;

  -- none exists yet: open one. It will be 'forming' until it reaches 10.
  if target is null then
    insert into squadrons (module_code, study_time)
    values (mod, stime)
    returning id into target;
  end if;

  insert into squadron_members (squadron_id, user_id)
  values (target, uid)
  on conflict do nothing;

  update squadrons
     set status = case
       when (select count(*) from squadron_members m where m.squadron_id = target) >= 10
       then 'active' else 'forming' end
   where id = target;

  return target;
end $$;

-- The return type loses a column, so create or replace is not enough — the
-- signature has to be dropped first. Nothing in the client reads the result of
-- this one today, so the narrower shape breaks no caller.
drop function if exists squadron_roster(text, uuid);

create function squadron_roster(uid text, sid uuid)
returns table (user_id text, callsign text, marking text, is_staff boolean, joined_at timestamptz)
language sql
stable
as $$
  select m.user_id, p.callsign, m.marking,
         coalesce(p.is_staff, false), m.joined_at
    from squadron_members m
    left join pilot_profiles p on p.user_id = m.user_id
   where m.squadron_id = sid
     and m.user_id not in (select blocked_id from blocks where blocks.user_id = uid)
     and m.user_id not in (select b.user_id from blocks b where b.blocked_id = uid)
   order by m.joined_at;
$$;

-- ------------------------------------------------------------------ columns

alter table pilot_profiles drop column if exists livery;
alter table squadrons      drop column if exists livery;
