-- ============================================================================
-- Wingman — complete schema, migrations 0005 → 0013
--
-- Generated by scripts/build-migration-bundle.mjs. Do not edit by hand: edit
-- the numbered files in supabase/migrations/ and regenerate.
--
-- Every statement is idempotent, so this is safe to run on a fresh database or
-- on one that already has some of it. Run it as one paste, top to bottom.
--
-- Assumes 0001-0004 are already applied (social layer, threaded posts,
-- reactions/attempts/completions, progress merge).
-- ============================================================================

-- ############################################################################
-- 0005_squadrons_safety_comms.sql
-- ############################################################################

-- Wingman — squadrons, safety, calls, comms
-- Covers SPEC.md build steps 2, 4, 8 and 9. Run after 0004. Safe to re-run.

-- ---------------------------------------------------------------- profiles
-- Onboarding answers and identity. §7.1 collects study_time; §2 needs livery.
create table if not exists pilot_profiles (
  user_id       text primary key,
  callsign      text,
  livery        text        not null default 'dawn-patrol',
  variant_pin   text,                                   -- 'day' | 'night' | null = auto
  study_time    text,                                   -- 'early' | 'day' | 'evening' | 'late'
  invisible     boolean     not null default false,     -- §8.3, no penalty
  glow_enabled  boolean     not null default true,      -- §7.6 toggle
  is_staff      boolean     not null default false,     -- §7.1, badged real people only
  created_at    timestamptz not null default now()
);

-- --------------------------------------------------------------- squadrons
-- §7.1. Target 10-20 members. A squadron below 10 is 'forming' and says so.
create table if not exists squadrons (
  id           uuid        primary key default gen_random_uuid(),
  module_code  text        not null,
  livery       text        not null default 'dawn-patrol',   -- §2.12, group vote
  study_time   text,
  status       text        not null default 'forming',       -- 'forming' | 'active'
  created_at   timestamptz not null default now()
);

create table if not exists squadron_members (
  squadron_id uuid        not null references squadrons (id) on delete cascade,
  user_id     text        not null,
  marking     text        not null default 'solid',     -- §2.9 collision markings
  joined_at   timestamptz not null default now(),
  primary key (squadron_id, user_id)
);
create index if not exists squadron_members_user_idx on squadron_members (user_id);

-- ------------------------------------------------------------------ safety
-- §9. Must exist before any user-generated content ships.
create table if not exists blocks (
  user_id    text not null,
  blocked_id text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, blocked_id),
  check (user_id <> blocked_id)
);

create table if not exists mutes (
  user_id   text not null,
  muted_id  text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, muted_id)
);

create table if not exists reports (
  id          uuid        primary key default gen_random_uuid(),
  reporter_id text        not null,
  target_type text        not null,          -- 'message' | 'image' | 'user'
  target_id   text        not null,
  reason      text,
  chapter_id  text,
  channel_id  text,
  status      text        not null default 'open',   -- 'open' | 'actioned' | 'dismissed'
  created_at  timestamptz not null default now()
);
create index if not exists reports_open_idx on reports (status, created_at) where status = 'open';

-- ------------------------------------------------------------------- calls
-- §7.7. A Call must never expire unanswered without telling the caller.
create table if not exists calls (
  id           uuid        primary key default gen_random_uuid(),
  user_id      text        not null,
  chapter_id   text        not null,
  question_id  text,
  body         text,
  status       text        not null default 'open',   -- 'open' | 'answered' | 'surfaced'
  stage        smallint    not null default 0,        -- 0 none, 1 squadron, 2 widened, 3 told caller
  created_at   timestamptz not null default now()
);
create index if not exists calls_open_idx on calls (status, created_at) where status = 'open';

create table if not exists call_responses (
  id         uuid        primary key default gen_random_uuid(),
  call_id    uuid        not null references calls (id) on delete cascade,
  user_id    text        not null,
  body       text        not null,
  created_at timestamptz not null default now()
);

create table if not exists call_nudges (
  call_id    uuid        not null references calls (id) on delete cascade,
  user_id    text        not null,
  created_at timestamptz not null default now(),
  primary key (call_id, user_id)          -- §7.7: at most one nudge per member per call
);

-- ------------------------------------------------------------------- comms
-- §7.8. A continuous channel per module. Not a forum: no threads, no votes.
create table if not exists comms_messages (
  id            uuid        primary key default gen_random_uuid(),
  module_code   text        not null,
  squadron_id   uuid        references squadrons (id) on delete cascade,
  user_id       text        not null,
  body          text,
  image_url     text,
  chapter_id    text,                                  -- the chapter chip
  pinned_to     text,                                  -- pinned to this chapter
  is_system     boolean     not null default false,    -- §8.1 Wingman opener
  created_at    timestamptz not null default now(),
  edited_at     timestamptz
);
create index if not exists comms_channel_idx on comms_messages (module_code, created_at desc);
create index if not exists comms_pinned_idx on comms_messages (pinned_to) where pinned_to is not null;

create table if not exists comms_reactions (
  message_id uuid not null references comms_messages (id) on delete cascade,
  user_id    text not null,
  emoji      text not null,
  primary key (message_id, user_id, emoji)
);

-- -------------------------------------------------------------- formations
-- §7.9. Temporary, 2-6 people, one chapter. Nobody loses a Formation.
create table if not exists formations (
  id          uuid        primary key default gen_random_uuid(),
  chapter_id  text        not null,
  module_code text        not null,
  squadron_id uuid        references squadrons (id) on delete set null,
  started_at  timestamptz not null default now(),
  ended_at    timestamptz
);

create table if not exists formation_members (
  formation_id uuid not null references formations (id) on delete cascade,
  user_id      text not null,
  joined_at    timestamptz not null default now(),
  left_at      timestamptz,
  primary key (formation_id, user_id)
);

-- --------------------------------------------------------------------- RLS
do $$
declare t text;
begin
  foreach t in array array[
    'pilot_profiles','squadrons','squadron_members','blocks','mutes','reports',
    'calls','call_responses','call_nudges','comms_messages','comms_reactions',
    'formations','formation_members'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists %I on %I', t || '_open', t);
    execute format('create policy %I on %I for all using (true) with check (true)', t || '_open', t);
  end loop;
end $$;

-- ------------------------------------------------------- the fill ladder
-- §7.1. Descends the four rungs and stops at the first that reaches 10.
-- Never invents a member: if rung 4 still falls short the squadron stays
-- 'forming' and the UI says so plainly.
create or replace function assign_squadron(uid text, mod text, stime text)
returns uuid
language plpgsql
as $$
declare target uuid;
begin
  -- already placed for this module?
  select s.id into target
    from squadron_members m join squadrons s on s.id = m.squadron_id
   where m.user_id = uid and s.module_code = mod
   limit 1;
  if target is not null then return target; end if;

  -- rung 1: same module, same study-time, with room
  select s.id into target from squadrons s
   where s.module_code = mod and s.study_time is not distinct from stime
     and (select count(*) from squadron_members m where m.squadron_id = s.id) < 20
   order by (select count(*) from squadron_members m where m.squadron_id = s.id) desc
   limit 1;

  -- rung 2: same module, any study-time
  if target is null then
    select s.id into target from squadrons s
     where s.module_code = mod
       and (select count(*) from squadron_members m where m.squadron_id = s.id) < 20
     order by (select count(*) from squadron_members m where m.squadron_id = s.id) desc
     limit 1;
  end if;

  -- rung 3: any module, same study-time
  if target is null then
    select s.id into target from squadrons s
     where s.study_time is not distinct from stime
       and (select count(*) from squadron_members m where m.squadron_id = s.id) < 20
     order by (select count(*) from squadron_members m where m.squadron_id = s.id) desc
     limit 1;
  end if;

  -- rung 4: any squadron with room
  if target is null then
    select s.id into target from squadrons s
     where (select count(*) from squadron_members m where m.squadron_id = s.id) < 20
     order by (select count(*) from squadron_members m where m.squadron_id = s.id) desc
     limit 1;
  end if;

  -- none exists yet: open one. It will be 'forming' until it reaches 10.
  if target is null then
    insert into squadrons (module_code, study_time, livery)
    values (mod, stime, 'dawn-patrol')
    returning id into target;
  end if;

  insert into squadron_members (squadron_id, user_id)
  values (target, uid)
  on conflict do nothing;

  update squadrons
     set status = case
       when (select count(*) from squadron_members m where m.squadron_id = target) >= 10
       then 'active' else 'forming' end
   where id = target;

  return target;
end $$;

-- Squadron roster with everything the UI needs, minus anyone blocked either way.
create or replace function squadron_roster(uid text, sid uuid)
returns table (user_id text, callsign text, livery text, marking text, is_staff boolean, joined_at timestamptz)
language sql
stable
as $$
  select m.user_id, p.callsign, coalesce(p.livery, 'dawn-patrol'), m.marking,
         coalesce(p.is_staff, false), m.joined_at
    from squadron_members m
    left join pilot_profiles p on p.user_id = m.user_id
   where m.squadron_id = sid
     and m.user_id not in (select blocked_id from blocks where blocks.user_id = uid)
     and m.user_id not in (select b.user_id from blocks b where b.blocked_id = uid)
   order by m.joined_at;
$$;


-- ############################################################################
-- 0006_openers_rate_limits_moderation.sql
-- ############################################################################

-- §8.1 the app speaks first · §9 rate limits and the moderation queue
--
-- Everything here is idempotent and safe to re-run.

-- ---------------------------------------------------------------- openers
-- The quiet check and the insert have to happen together. Done in the client
-- they race: two people opening a quiet channel at the same moment both see it
-- as quiet and both post. This does it in one statement under one lock.
create or replace function post_opener_if_quiet(mod text, chap text, opener text)
returns uuid
language plpgsql
as $$
declare
  newest    timestamptz;
  human_wk  integer;
  new_id    uuid;
begin
  if opener is null or length(btrim(opener)) = 0 then return null; end if;

  -- Serialise per channel so concurrent callers queue rather than collide.
  perform pg_advisory_xact_lock(hashtext('opener:' || mod));

  select max(created_at) into newest
    from comms_messages where module_code = mod;

  -- Anything at all inside 48 hours means the channel is not quiet, including
  -- a previous opener -- which is what caps this at one per channel per 48h.
  if newest is not null and newest > now() - interval '48 hours' then
    return null;
  end if;

  select count(*) into human_wk
    from comms_messages
   where module_code = mod
     and is_system = false
     and created_at > now() - interval '7 days';

  if human_wk >= 20 then return null; end if;

  insert into comms_messages (module_code, user_id, body, chapter_id, is_system)
  values (mod, 'wingman', opener, chap, true)
  returning id into new_id;

  return new_id;
end $$;

-- ------------------------------------------------------------ rate limits
-- §9: composer posts, Calls and Formation invites are limited per user per
-- hour. Enforced here because a client-side guard is decoration.
create table if not exists rate_events (
  id         bigserial   primary key,
  user_id    text        not null,
  kind       text        not null,          -- 'message' | 'call' | 'formation'
  created_at timestamptz not null default now()
);
create index if not exists rate_events_lookup
  on rate_events (user_id, kind, created_at desc);

create or replace function rate_limit_take(uid text, k text, per_hour integer)
returns boolean
language plpgsql
as $$
declare used integer;
begin
  if uid is null then return false; end if;
  perform pg_advisory_xact_lock(hashtext('rate:' || uid || ':' || k));
  select count(*) into used
    from rate_events
   where user_id = uid and kind = k and created_at > now() - interval '1 hour';
  if used >= per_hour then return false; end if;
  insert into rate_events (user_id, kind) values (uid, k);
  return true;
end $$;

-- Housekeeping: nothing reads an event older than an hour.
create or replace function rate_events_prune()
returns void language sql as $$
  delete from rate_events where created_at < now() - interval '2 hours';
$$;

-- ------------------------------------------------------- moderation queue
-- §9: reports route to a human queue with the message, the chapter context and
-- the channel. Target first response within 24 hours, so the view carries the
-- age and the flag rather than making a person work it out.
create or replace view moderation_queue as
select
  r.id,
  r.created_at,
  r.reporter_id,
  r.target_type,
  r.target_id,
  r.reason,
  r.chapter_id,
  r.channel_id,
  r.status,
  now() - r.created_at                              as waiting,
  (now() - r.created_at) > interval '24 hours'      as past_target,
  m.body                                            as message_body,
  m.user_id                                         as message_author,
  m.module_code                                     as message_channel
from reports r
left join comms_messages m
  on r.target_type = 'message' and m.id::text = r.target_id
where r.status = 'open'
order by r.created_at;

do $$
begin
  execute 'alter table rate_events enable row level security';
  execute 'drop policy if exists rate_events_open on rate_events';
  execute 'create policy rate_events_open on rate_events for all using (true) with check (true)';
end $$;


-- ############################################################################
-- 0007_questions_squawks_teams.sql
-- ############################################################################

-- Phase 4 — §9.3.4 question-as-atom · §9.4.2 squawk · §9.4.3 teams ·
-- §9.4.4 standing · §9.4.5 notifications · §11 verified tier
--
-- Idempotent, and safe to re-run. Requires 0005.

-- ------------------------------------------------- §9.3.4 the atom is a question
-- A chat log is worthless a week later: the answer to "why is B wrong" scrolls
-- away. Marking a message as a question, and a reply as answering it, is what
-- lets settled knowledge separate from chatter.
alter table comms_messages add column if not exists is_question  boolean not null default false;
alter table comms_messages add column if not exists answers_id   uuid references comms_messages (id) on delete set null;
alter table comms_messages add column if not exists resolved_at  timestamptz;
-- §11 — a visually distinct verified tier, from day one.
alter table comms_messages add column if not exists is_verified  boolean not null default false;
alter table comms_messages add column if not exists verified_by  text;

create index if not exists comms_questions_idx
  on comms_messages (chapter_id, created_at desc) where is_question;
create index if not exists comms_answers_idx
  on comms_messages (answers_id) where answers_id is not null;

-- ------------------------------------------------------------ §9.4.2 squawk
-- Real aviation semantics: 7600 is radio failure ("I've read this three times
-- and I don't get it"), 7700 is emergency ("checkride Thursday and I'm lost").
--
-- The code sits on the question itself. Putting it on a parallel `calls` row
-- would mean two places to look and one of them usually empty.
alter table comms_messages add column if not exists squawk text;
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'comms_squawk_code') then
    alter table comms_messages add constraint comms_squawk_code
      check (squawk is null or squawk in ('7600', '7700')) not valid;
  end if;
end $$;

-- §9.4.3 — "either now or scheduled (tonight 20:00)". 0005 gave formations a
-- started_at; a scheduled one needs a start in the future.
alter table formations add column if not exists starts_at timestamptz;

-- ------------------------------------------------------------- §9.4.3 teams
-- Self-formed, 3-6 people, persistent, their own chat. The strongest retention
-- mechanic in the plan: people come back for their group, not for the app.
create table if not exists teams (
  id          uuid        primary key default gen_random_uuid(),
  name        text        not null,
  module_code text,
  created_by  text        not null,
  created_at  timestamptz not null default now()
);

create table if not exists team_members (
  team_id   uuid        not null references teams (id) on delete cascade,
  user_id   text        not null,
  joined_at timestamptz not null default now(),
  primary key (team_id, user_id)
);
create index if not exists team_members_user_idx on team_members (user_id);

-- Team chat reuses comms_messages, scoped by team.
alter table comms_messages add column if not exists team_id uuid references teams (id) on delete cascade;
create index if not exists comms_team_idx on comms_messages (team_id, created_at desc) where team_id is not null;

-- ------------------------------------------- §9.4.4 standing · §11 status ladder
-- Standing is earned by helping, never by grinding chapters. The ladder is the
-- moderation model, not a gamification nicety: CFI unlocks marking an
-- explanation verified.
alter table pilot_profiles add column if not exists status  text    not null default 'student';
alter table pilot_profiles add column if not exists helped  integer not null default 0;
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'pilot_status_ladder') then
    alter table pilot_profiles add constraint pilot_status_ladder
      check (status in ('student', 'private', 'instrument', 'commercial', 'cfi')) not valid;
  end if;
end $$;

-- §9.4.5 — replies to you, your teams, and answers to your questions. Nothing
-- else, unless you opt in.
alter table pilot_profiles add column if not exists notify text not null default 'default';

-- ------------------------------------------------------ §10 per-module rollout
-- "Don't ship a social surface where it's empty. Turn it on per module once
-- there's content." A module with no social surface is fine; one with a visibly
-- abandoned surface is not.
create table if not exists module_social (
  module_code text primary key,
  enabled     boolean not null default false,
  enabled_at  timestamptz
);

do $$
declare t text;
begin
  foreach t in array array['teams', 'team_members', 'module_social'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists %I on %I', t || '_open', t);
    execute format('create policy %I on %I for all using (true) with check (true)', t || '_open', t);
  end loop;
end $$;

-- ------------------------------------------------------------- open squawks
-- §9.4 band 2: unanswered questions from every chapter, with context attached.
-- This is the room's purpose and the reason it is never empty.
create or replace view open_squawks as
select
  q.id,
  q.user_id,
  q.body,
  q.chapter_id,
  q.module_code,
  q.created_at,
  q.squawk,
  now() - q.created_at as waiting
from comms_messages q
where q.is_question
  and q.resolved_at is null
  and not exists (select 1 from comms_messages a where a.answers_id = q.id)
order by q.created_at;

-- Marking an answer bumps the helper's standing and resolves the question.
create or replace function mark_answer(answer_id uuid, question_id uuid, marker text)
returns boolean
language plpgsql
as $$
declare asker text; helper text;
begin
  select user_id into asker  from comms_messages where id = question_id and is_question;
  select user_id into helper from comms_messages where id = answer_id;
  if asker is null or helper is null then return false; end if;
  -- Only the person who asked decides what answered it.
  if marker is distinct from asker then return false; end if;

  update comms_messages set answers_id = question_id where id = answer_id;
  update comms_messages set resolved_at = now() where id = question_id;
  -- §9.4.4 — count helping, never grinding.
  if helper is distinct from asker then
    update pilot_profiles set helped = helped + 1 where user_id = helper;
  end if;
  return true;
end $$;


-- ############################################################################
-- 0008_lesson_surface.sql
-- ############################################################################

-- Wingman — the lesson surface: notes, threads and replies
--
-- Run after 0007. Safe to re-run. Additive only: it creates three tables and
-- two functions and touches nothing that exists.
--
-- RUN against the live project, and the client is now pointed at it. Verified
-- on 2026-08-31 by connecting and looking, not inferred: all three tables
-- exist, both functions are in pg_proc with matching signatures, and the
-- lesson_threads_anchor_whole CHECK is present.
--
-- This header said "NOT YET RUN" for a while after it had been. That is the
-- same failure the squadron.js comments carry, and the reason nothing in this
-- project should trust a comment about deployment state: `npm run check:backend`
-- and `npm run check:threads` are the source of truth. Run them.
--
-- THE ONE RULE THIS SCHEMA ENFORCES, because it cannot be enforced by
-- remembering it: a thread with a lesson carries the moment it is anchored to,
-- and a thread without one carries neither. That asymmetry is the whole reason
-- a module post can never appear under a video — there is nothing to attach it
-- to — and it is a CHECK constraint here rather than a convention in a comment.

-- ------------------------------------------------------------------- notes
-- Private, and never returned to anyone else. RLS is open like every other
-- table in this project (the client is anonymous from Postgres' point of view
-- and access control happens in the app), so the app must always filter by
-- author_id. There is no second reader of this table.
--
-- body may be EMPTY. A bare pin is a valid note and is the point of the
-- feature: the real cost of taking notes during a lesson is not typing speed,
-- it is that writing makes you miss the next thing.
create table if not exists lesson_notes (
  id         text        primary key,
  user_id    text        not null,
  lesson_id  text        not null,
  t          integer     not null check (t >= 0),
  body       text        not null default '',
  created_at timestamptz not null default now()
);
create index if not exists lesson_notes_user_idx on lesson_notes (user_id, lesson_id, t);

alter table lesson_notes enable row level security;
create policy lesson_notes_open on lesson_notes for all using (true) with check (true);

-- ----------------------------------------------------------------- threads
-- ONE TABLE, TWO QUERIES. The comment under the video and the thread in People
-- are the same row: the lesson asks what is on this lesson, People asks what is
-- in this module. Nothing copies, nothing syncs, nothing can drift.
--
-- Do not add a second table and a job that keeps them matching. That is the
-- version that ends up showing different reply counts in two places, and it is
-- the obvious implementation, which is why it is said here as well as in the
-- source.
create table if not exists lesson_threads (
  id         text        primary key,
  module_id  text        not null,
  lesson_id  text,                      -- null = a module post, People only
  t          integer,                   -- null iff lesson_id is null
  body       text        not null check (length(btrim(body)) > 0),
  author_id  text        not null,
  created_at timestamptz not null default now(),
  -- Anchored or not, never half. A row with a lesson and no moment would
  -- appear under a video with nowhere to sit on the bar; a row with a moment
  -- and no lesson would be a mark on a bar that belongs to no video.
  constraint lesson_threads_anchor_whole
    check ((lesson_id is null and t is null) or (lesson_id is not null and t is not null and t >= 0))
);
create index if not exists lesson_threads_module_idx on lesson_threads (module_id, created_at desc);
create index if not exists lesson_threads_lesson_idx on lesson_threads (module_id, lesson_id, t);

alter table lesson_threads enable row level security;
create policy lesson_threads_open on lesson_threads for all using (true) with check (true);

-- ----------------------------------------------------------------- replies
-- A reply belongs to the thread, never to a moment. It gets no timestamp of
-- its own and no mark on the bar — a good discussion would otherwise put
-- twelve marks on one spot and the bar would stop meaning anything.
--
-- Flat, not nested. parent_id is deliberately absent: a tree earns its keep at
-- ten thousand comments, not at forty, and adding it later is a column rather
-- than a migration of the rows.
create table if not exists lesson_replies (
  id         text        primary key,
  thread_id  text        not null references lesson_threads (id) on delete cascade,
  body       text        not null check (length(btrim(body)) > 0),
  author_id  text        not null,
  created_at timestamptz not null default now()
);
create index if not exists lesson_replies_thread_idx on lesson_replies (thread_id, created_at);

alter table lesson_replies enable row level security;
create policy lesson_replies_open on lesson_replies for all using (true) with check (true);

-- ------------------------------------------------------------- the two reads
-- Under the video: anchored threads on this lesson, in MOMENT order. Not
-- newest-first — ordering by moment is what makes scrolling the comment list
-- the same gesture as scrubbing the video, and it matches the bar above it.
create or replace function lesson_comments(p_module text, p_lesson text)
returns table (
  id text, module_id text, lesson_id text, t integer,
  body text, author_id text, created_at timestamptz, reply_count bigint
)
language sql
stable
as $$
  select th.id, th.module_id, th.lesson_id, th.t, th.body, th.author_id, th.created_at,
         count(r.id) as reply_count
  from lesson_threads th
  left join lesson_replies r on r.thread_id = th.id
  where th.module_id = p_module
    and th.lesson_id = p_lesson
  group by th.id
  order by th.t asc;
$$;

-- People: every thread in the module, with what a badge has to be measured
-- against. last_activity_by is the last thing that happened here that WASN'T
-- you, and it is null when the only activity is your own.
--
-- That second half is the one that is easy to miss. Measured against plain
-- last activity, a question you asked and nobody has answered badges itself —
-- you get a dot for your own post, forever, on every thread you start. That is
-- how People turns permanently red, which is the failure the module chat room
-- was rejected for.
create or replace function module_threads(p_module text, p_me text)
returns table (
  id text, lesson_id text, t integer, body text, author_id text,
  created_at timestamptz, reply_count bigint,
  in_it boolean, waiting boolean, last_activity_by timestamptz
)
language sql
stable
as $$
  select th.id, th.lesson_id, th.t, th.body, th.author_id, th.created_at,
         count(r.id)                                                     as reply_count,
         -- coalesce, because bool_or over an all-NULL set is NULL: a thread
         -- with no replies yields `th.author_id = p_me or NULL`, which is NULL
         -- rather than false for everyone else's unanswered questions.
         coalesce(bool_or(th.author_id = p_me or r.author_id = p_me), false) as in_it,
         count(r.id) = 0                                                  as waiting,
         -- greatest() ignores NULLs and returns NULL only when every argument
         -- is NULL, which is exactly the "the only activity here is yours"
         -- case the badge rule needs.
         greatest(
           case when th.author_id <> p_me then th.created_at end,
           max(r.created_at) filter (where r.author_id <> p_me)
         )                                                                as last_activity_by
  from lesson_threads th
  left join lesson_replies r on r.thread_id = th.id
  where th.module_id = p_module
  group by th.id
  -- In it, then waiting for an answer, then the rest. Newest-first is the
  -- wrong default here: the middle band is what turns eleven people into
  -- eleven people helping each other rather than everyone posting into silence.
  order by
    case when coalesce(bool_or(th.author_id = p_me or r.author_id = p_me), false) then 0
         when count(r.id) = 0 then 1
         else 2 end,
    greatest(th.created_at, coalesce(max(r.created_at), th.created_at)) desc;
$$;


-- ############################################################################
-- 0009_right_seat_boundary.sql
-- ############################################################################

-- Wingman — §7, the right seat's boundary, on the server
--
-- Run after 0008. Safe to re-run. Additive only: it creates two functions and
-- one policy and alters no table.
--
-- ===========================================================================
-- READ THIS BEFORE WRITING A POLICY THAT MENTIONS auth.uid()
-- ===========================================================================
-- It will not work, and it will not fail loudly either — it will silently deny
-- every row and the room will look empty rather than broken.
--
-- Clerk owns identity in this project. The browser talks to PostgREST with the
-- ANON key and nothing else: there is no Supabase session, no JWT carrying a
-- user, and auth.uid() is NULL on every single request. That is why every
-- table in this codebase carries `using (true)` and why user_id columns hold a
-- Clerk id as text rather than a Supabase uid. It is a deliberate
-- architecture, written down in CLAUDE.md, not an oversight to be corrected in
-- passing by a migration.
--
-- WHAT THIS MIGRATION THEREFORE IS. §7 says: only people you share a squadron
-- with may ever appear in the right seat. Until this file that sentence lived
-- only in JavaScript, in roomModel.rightSeatCandidates, which means it held
-- exactly as long as every present and future caller remembered to route
-- through that function — and the room had ALREADY forgotten once, handing the
-- raw presence list straight to the view.
--
-- So the boundary is expressed here as a function that cannot return a
-- stranger, whatever the caller asks for. The client calls right_seat(me)
-- instead of selecting presence and filtering afterwards. A caller that passes
-- somebody else's id gets that person's squadron-mates rather than their own,
-- which is a lateral move and not an escalation: presence is already readable
-- to the anon key, as it has to be for the online rail to work at all.
--
-- WHAT THIS IS NOT: authentication. It is one statement of the rule, in the
-- place the rule is applied, so a second caller cannot quietly disagree with
-- the first. Turning it into enforcement needs Clerk JWTs accepted by Supabase
-- so that auth.jwt()->>'sub' is trustworthy; at that point the `p_me`
-- parameter is deleted, every function below reads the subject from the token,
-- and the open policies are narrowed. That is a project, not a line, and it is
-- the same project for all thirty-odd tables at once — doing it for this one
-- would leave the codebase with two auth models, which is worse than one
-- honest one.
-- ===========================================================================

-- --------------------------------------------------------------- §7 helper
-- The squadrons an account is actually in. Its own function because three
-- things below need it and a copied subquery is a rule with three owners.
create or replace function my_squadron_ids(p_me text)
returns setof uuid
language sql
stable
as $$
  select squadron_id from squadron_members where user_id = p_me;
$$;

-- ------------------------------------------------------------ §7 right seat
-- Who is in the room right now that p_me shares a squadron with, minus anyone
-- either of them has blocked.
--
-- The blocks check runs BOTH WAYS on purpose. Blocking is not a mute: if A
-- blocks B then B must not be offered A's seat either, or the block is
-- trivially defeated by the blocked person doing the inviting.
create or replace function right_seat(p_me text, p_since interval default '90 seconds')
returns table (
  user_id      text,
  squadron_id  uuid,
  module_code  text,
  chapter_id   text,
  last_seen    timestamptz
)
language sql
stable
as $$
  select distinct on (p.user_id)
         p.user_id,
         sm.squadron_id,
         p.module_code,
         p.chapter_id,
         p.last_seen
  from presence p
  join squadron_members sm
    on sm.user_id = p.user_id
   and sm.squadron_id in (select my_squadron_ids(p_me))
  where p.user_id <> p_me
    and p.last_seen >= now() - p_since
    and not exists (
      select 1 from blocks b
      where (b.user_id = p_me and b.blocked_id = p.user_id)
         or (b.user_id = p.user_id and b.blocked_id = p_me)
    )
  order by p.user_id, p.last_seen desc;
$$;

-- --------------------------------------------------------- the one narrowing
-- lesson_notes is the single table in this schema with exactly one legitimate
-- reader — the person who wrote the note. Every other table here is shared by
-- design, so `using (true)` is an accurate description of them. This one it
-- was never accurate about: it said "anyone may read anyone's private notes",
-- and the only thing standing between that and the notes was the app
-- remembering to filter by author_id on every query it will ever write.
--
-- It cannot be narrowed to the AUTHOR without a JWT, per the header. It can be
-- narrowed to "not readable in bulk at all", which is a real reduction: a
-- policy of `false` for select means notes cannot be enumerated over REST by
-- anyone, and the app reads them where it always has — through user_progress,
-- which is where the client actually keeps them today.
--
-- Writes stay open so the table remains usable the moment a JWT exists and the
-- notes move here properly.
drop policy if exists lesson_notes_open on lesson_notes;

create policy lesson_notes_no_bulk_read on lesson_notes
  for select using (false);
create policy lesson_notes_write on lesson_notes
  for insert with check (true);
create policy lesson_notes_update on lesson_notes
  for update using (true) with check (true);
create policy lesson_notes_delete on lesson_notes
  for delete using (true);


-- ############################################################################
-- 0010_thread_titles_and_answers.sql
-- ############################################################################

-- Wingman — thread titles, best answers, and answer votes
--
-- Run after 0009. Safe to re-run. Additive only: three columns and one table.
-- Nothing existing changes shape, so a client that has not been updated keeps
-- working against these tables exactly as before.
--
-- WHY THESE THREE AND NOT MORE. The Ready Room rebuild turns a module's
-- discussion into a question feed: a list of titled questions, each with
-- answers, one of which the asker can mark as the one that worked. Those are
-- the only three facts the schema could not already hold.
--
-- ------------------------------------------------------------------- title
-- A thread created IN the Ready Room is a question and needs a title, because
-- a feed of untitled paragraphs cannot be scanned.
--
-- A thread MIRRORED from a lesson comment has no title and must not be given
-- one: adding a title field to the lesson comment box would put a form in
-- front of a casual remark, and casual commenting on a lesson has to stay
-- frictionless. Those rows keep title NULL and the client shows the comment's
-- first line instead, with a FROM LESSON tag that both explains the shorter
-- title and links back.
--
-- So the column is NULLABLE on purpose, and null means "this came from a
-- lesson". That is the same asymmetry 0008 already encodes with lesson_id and
-- t, and it is why there is no CHECK forcing a title: half these rows must
-- never have one.
alter table lesson_threads add column if not exists title text;

-- ------------------------------------------------------------- best answer
-- The asker's mark, not a vote count. "Which answer actually worked" is a
-- judgement only the person who asked can make, and it is one per thread,
-- which is why it lives here as a single column rather than as a flag on the
-- replies where two rows could both claim it.
--
-- ON DELETE SET NULL: deleting the chosen answer must not delete the question.
alter table lesson_threads
  add column if not exists best_reply_id text
  references lesson_replies (id) on delete set null;

-- ------------------------------------------------------------------- votes
-- One row per person per answer, so the primary key IS the "one vote each"
-- rule. A count column would need a second write to stay true and would drift;
-- this cannot.
--
-- No value column. post_votes carries value +1/-1 for the older social layer,
-- and this deliberately does not: an answer can be endorsed, not buried. A
-- downvote on somebody's attempt to help is the thing that stops people
-- answering.
create table if not exists lesson_reply_votes (
  reply_id   text        not null references lesson_replies (id) on delete cascade,
  user_id    text        not null,
  created_at timestamptz not null default now(),
  primary key (reply_id, user_id)
);
create index if not exists lesson_reply_votes_reply_idx on lesson_reply_votes (reply_id);

alter table lesson_reply_votes enable row level security;
-- Open, like every other table in this project: the client is anonymous from
-- Postgres' point of view and access control happens in the app. See 0009's
-- header before writing a policy that mentions auth.uid() here.
create policy lesson_reply_votes_open on lesson_reply_votes
  for all using (true) with check (true);


-- ############################################################################
-- 0011_discovery.sql
-- ############################################################################

-- Wingman — discovery: how a student who knows nobody reaches somebody
--
-- Run after 0010. Safe to re-run. Adds columns to two existing tables, creates
-- two tables and a set of functions. Alters no existing column and drops
-- nothing.
--
-- ===========================================================================
-- THE BOUNDARY LIVES HERE, NOT IN THE CLIENT
-- ===========================================================================
-- Read the header of 0009 first; the same architecture applies and for the
-- same reason. auth.uid() is NULL on every request, every table carries
-- `using (true)`, and the browser holds the anon key. So a rule expressed only
-- as "the UI does not call that endpoint" is not a rule — PostgREST will serve
-- the table to anyone who asks.
--
-- The rule this file has to hold is §3 of the brief: a person may appear in
-- search only if the searcher already shares a squadron with them, or that
-- person has answered in a module the searcher studies. Some of these students
-- are under 18. An app where an adult can search a minor by name is a grooming
-- vector, and "the client happens not to send that query" is not a defence.
--
-- So people_search is a function that cannot return a stranger whatever it is
-- asked for. It is not authentication — passing another user's id returns
-- THEIR orbit, which is a lateral move, the same trade 0009 documents — it is
-- one statement of the rule in the place the rule applies, so a second caller
-- cannot quietly disagree with the first.
-- ===========================================================================

-- ------------------------------------------------------------- 1 · squadrons
-- The table from 0005 has no name, which is why every squadron in the client
-- is currently identified by its module code. Discovery needs a room to be a
-- named thing you can be told about.
alter table squadrons add column if not exists name         text;
alter table squadrons add column if not exists blurb        text;
alter table squadrons add column if not exists owner_id     text;
alter table squadrons add column if not exists exam_window  text;

-- open        anyone may join immediately
-- request     joining creates a row in squadron_join_requests
-- invite_only the default, and the only way in is a link or an invite
alter table squadrons add column if not exists join_policy  text not null default 'invite_only';
do $$ begin
  alter table squadrons add constraint squadrons_join_policy_known
    check (join_policy in ('open', 'request', 'invite_only'));
exception when duplicate_object then null; end $$;

-- PER SQUADRON, NOT GLOBAL. 32 is a full class of 28 plus a repeat student, a
-- late joiner and an instructor. Open rooms are left NULL — uncapped — because
-- a cohort room that fills up locks out exactly the newcomers it exists for.
-- The brief flags this number as the one open decision; it is a default on a
-- column, so changing it is one statement rather than a migration of logic.
alter table squadrons add column if not exists member_cap   integer default 32;

-- The shareable link. One per squadron, regenerated by revoking.
alter table squadrons add column if not exists invite_token       text;
alter table squadrons add column if not exists invite_expires_at  timestamptz;
alter table squadrons add column if not exists invite_revoked_at  timestamptz;
create unique index if not exists squadrons_invite_token_idx
  on squadrons (lower(invite_token)) where invite_token is not null;

-- ------------------------------------------------------------- 2 · profiles
-- SET BY THE STUDENT, NEVER INFERRED. The brief is explicit: exam window and
-- active window are things a person says about themselves. Current module,
-- answer habit and study rhythm are derived below and deliberately not stored,
-- so they cannot drift from the behaviour they describe.
alter table pilot_profiles add column if not exists exam_window   text;
alter table pilot_profiles add column if not exists active_window text;   -- morning|afternoon|evening|night
alter table pilot_profiles add column if not exists timezone      text;
-- The opt-out. Removes a student from people-search entirely and leaves every
-- squadron they are already in untouched.
alter table pilot_profiles add column if not exists discoverable  boolean not null default true;

-- --------------------------------------------------------- 3 · new tables
-- A request is not a join. §8: nothing auto-joins anyone to anything, and an
-- invite cannot force-add — it is a request the invited person accepts.
create table if not exists squadron_join_requests (
  squadron_id uuid        not null references squadrons (id) on delete cascade,
  user_id     text        not null,
  state       text        not null default 'pending' check (state in ('pending','accepted','declined')),
  created_at  timestamptz not null default now(),
  decided_at  timestamptz,
  primary key (squadron_id, user_id)
);
create index if not exists squadron_join_requests_user_idx on squadron_join_requests (user_id, state);

-- Person-to-person, as distinct from the squadron's shareable link above.
-- "Invite to a squadron" on a profile writes one of these.
create table if not exists squadron_invites (
  id           uuid        primary key default gen_random_uuid(),
  squadron_id  uuid        not null references squadrons (id) on delete cascade,
  inviter_id   text        not null,
  invitee_id   text        not null,
  state        text        not null default 'pending' check (state in ('pending','accepted','declined','revoked')),
  created_at   timestamptz not null default now(),
  unique (squadron_id, invitee_id)
);
create index if not exists squadron_invites_invitee_idx on squadron_invites (invitee_id, state);

-- NO user_blocks TABLE. The brief lists one; `blocks` already exists from 0005
-- with exactly that shape and is already read by right_seat in 0009. A second
-- block list would be two owners of one fact, and the failure mode is the bad
-- one: a person blocked in one table and not the other is visible on whichever
-- surface reads the emptier list.

do $$
declare t text;
begin
  foreach t in array array['squadron_join_requests', 'squadron_invites'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists %I on %I', t || '_open', t);
    execute format('create policy %I on %I for all using (true) with check (true)', t || '_open', t);
  end loop;
end $$;

-- --------------------------------------------------------- 4 · the orbit
-- Modules an account actually studies. There is no enrollments table in this
-- database — CLAUDE.md says there is, and it is wrong — so this is built from
-- the two signals that do exist: a chapter you completed, or a thread you
-- posted. Both are activity in the module rather than a claim about it.
create or replace function my_modules(p_me text)
returns setof text
language sql
stable
as $$
  select module_code from chapter_completions where user_id = p_me
  union
  select module_id   from lesson_threads      where author_id = p_me;
$$;

-- THE ORBIT ITSELF, and every people-facing function below goes through it.
-- True when p_me may see p_them at all: a shared squadron, or p_them has
-- written in a module p_me studies.
create or replace function in_my_orbit(p_me text, p_them text)
returns boolean
language sql
stable
as $$
  select p_me is not null and p_them is not null and p_me <> p_them and (
    exists (
      select 1 from squadron_members a
      join squadron_members b on b.squadron_id = a.squadron_id
      where a.user_id = p_me and b.user_id = p_them
    )
    or exists (
      select 1 from lesson_threads t
      where t.author_id = p_them and t.module_id in (select my_modules(p_me))
    )
    or exists (
      select 1 from lesson_replies r
      join lesson_threads t on t.id = r.thread_id
      where r.author_id = p_them and t.module_id in (select my_modules(p_me))
    )
  );
$$;

-- ------------------------------------------------------ 5 · people search
-- The only way the client is allowed to look a person up. Scoped by orbit,
-- filtered by the opt-out, and blocked BOTH WAYS — blocking is symmetric and
-- total, so neither party appears to the other, on any surface.
create or replace function people_search(p_me text, p_q text)
returns table (user_id text, callsign text, module_code text, shares_squadron boolean)
language sql
stable
as $$
  select
    p.user_id,
    p.callsign,
    (select c.module_code from chapter_completions c
      where c.user_id = p.user_id order by c.completed_at desc limit 1) as module_code,
    exists (
      select 1 from squadron_members a
      join squadron_members b on b.squadron_id = a.squadron_id
      where a.user_id = p_me and b.user_id = p.user_id
    ) as shares_squadron
  from pilot_profiles p
  where p.discoverable
    and in_my_orbit(p_me, p.user_id)
    and not exists (select 1 from blocks b
                    where (b.user_id = p_me and b.blocked_id = p.user_id)
                       or (b.user_id = p.user_id and b.blocked_id = p_me))
    and coalesce(btrim(p_q), '') <> ''
    and p.callsign ilike '%' || btrim(p_q) || '%'
  order by shares_squadron desc, p.callsign
  limit 20;
$$;

-- --------------------------------------------------------- 6 · capacity
-- Headcount is its own function because three things below need it, and a
-- copied count(*) is a rule with three owners.
create or replace function squadron_headcount(p_squadron uuid)
returns integer
language sql
stable
as $$
  select count(*)::int from squadron_members where squadron_id = p_squadron;
$$;

-- Full only when a cap is actually set. NULL member_cap means uncapped, which
-- is what open cohort rooms use.
create or replace function squadron_is_full(p_squadron uuid)
returns boolean
language sql
stable
as $$
  select s.member_cap is not null and squadron_headcount(s.id) >= s.member_cap
  from squadrons s where s.id = p_squadron;
$$;

-- ------------------------------------------------------- 7 · discovery list
-- Rooms p_me could join, SORTED BY ACTIVITY RATHER THAN SIZE — a busy room of
-- nine beats a dead room of forty. `known` is the social-proof line: people
-- already in there that p_me has studied alongside.
--
-- Capacity is returned as a headcount and a boolean, never as a fraction. §2:
-- a group of eight is a squadron; rendered as "8 of 32" it becomes a
-- half-empty one, and that framing is what kills small groups.
create or replace function discover_squadrons(p_me text, p_filter text default 'all')
returns table (
  id uuid, name text, blurb text, module_code text, exam_window text,
  join_policy text, members integer, active_week integer, is_full boolean,
  known_ids text[], already_in boolean, requested boolean
)
language sql
stable
as $$
  with mine as (select squadron_id from squadron_members where user_id = p_me),
  active as (
    select m.squadron_id, count(distinct pr.user_id)::int as n
    from squadron_members m
    left join presence pr
      on pr.user_id = m.user_id and pr.last_seen > now() - interval '7 days'
    group by m.squadron_id
  )
  select
    s.id, s.name, s.blurb, s.module_code, s.exam_window, s.join_policy,
    squadron_headcount(s.id) as members,
    coalesce(a.n, 0) as active_week,
    coalesce(squadron_is_full(s.id), false) as is_full,
    coalesce((
      select array_agg(sm.user_id)
      from squadron_members sm
      where sm.squadron_id = s.id and in_my_orbit(p_me, sm.user_id)
    ), '{}') as known_ids,
    s.id in (select squadron_id from mine) as already_in,
    exists (select 1 from squadron_join_requests r
            where r.squadron_id = s.id and r.user_id = p_me and r.state = 'pending') as requested
  from squadrons s
  left join active a on a.squadron_id = s.id
  where s.join_policy in ('open', 'request')
    and (p_filter <> 'yours' or s.module_code in (select my_modules(p_me)))
    and (p_filter <> 'exam'  or s.exam_window is not distinct from
         (select pp.exam_window from pilot_profiles pp where pp.user_id = p_me))
  order by coalesce(a.n, 0) desc, squadron_headcount(s.id) desc
  limit 40;
$$;

-- ------------------------------------------------------------- 8 · joining
-- ONE DOOR. Every route in — the discovery card, the invite link, an accepted
-- person-to-person invite — comes through here, so the capacity rule and the
-- block rule cannot be true on one path and forgotten on another.
--
-- Returns the outcome as text rather than raising: the caller renders it, and
-- "full" is an ordinary answer rather than an error.
create or replace function join_squadron(p_me text, p_squadron uuid)
returns text
language plpgsql
volatile
as $$
declare s squadrons%rowtype;
begin
  select * into s from squadrons where id = p_squadron;
  if not found then return 'missing'; end if;
  if exists (select 1 from squadron_members where squadron_id = s.id and user_id = p_me)
    then return 'already_in'; end if;
  -- A blocked person cannot arrive by any route, including a link they were
  -- given before the block.
  if exists (
    select 1 from squadron_members m
    join blocks b on (b.user_id = p_me and b.blocked_id = m.user_id)
                  or (b.user_id = m.user_id and b.blocked_id = p_me)
    where m.squadron_id = s.id
  ) then return 'unavailable'; end if;
  if coalesce(squadron_is_full(s.id), false) then return 'full'; end if;

  if s.join_policy = 'open' then
    insert into squadron_members (squadron_id, user_id) values (s.id, p_me)
      on conflict do nothing;
    return 'joined';
  elsif s.join_policy = 'request' then
    insert into squadron_join_requests (squadron_id, user_id) values (s.id, p_me)
      on conflict (squadron_id, user_id) do update set state = 'pending', decided_at = null;
    return 'requested';
  else
    return 'invite_only';
  end if;
end $$;

-- --------------------------------------------------------- 9 · invite links
-- Resolving a link is a read that already knows every reason it might fail, so
-- the page can say which one. A revoked or expired token is 'missing' on
-- purpose: a link that says "this was revoked" tells a stranger the room
-- exists.
create or replace function squadron_by_invite(p_me text, p_token text)
returns table (id uuid, name text, blurb text, members integer, state text)
language sql
stable
as $$
  select s.id, s.name, s.blurb, squadron_headcount(s.id) as members,
    case
      when s.invite_revoked_at is not null then 'missing'
      when s.invite_expires_at is not null and s.invite_expires_at < now() then 'missing'
      when exists (select 1 from squadron_members m where m.squadron_id = s.id and m.user_id = p_me)
        then 'already_in'
      when exists (
        select 1 from squadron_members m
        join blocks b on (b.user_id = p_me and b.blocked_id = m.user_id)
                      or (b.user_id = m.user_id and b.blocked_id = p_me)
        where m.squadron_id = s.id
      ) then 'unavailable'
      when coalesce(squadron_is_full(s.id), false) then 'full'
      else 'ok'
    end as state
  from squadrons s
  where lower(s.invite_token) = lower(btrim(p_token));
$$;


-- ############################################################################
-- 0012_search_and_suggestions.sql
-- ############################################################################

-- Wingman — searchable names, and suggestions that rank rather than list
--
-- Run after 0011. Safe to re-run. Adds one column and replaces three functions.
--
-- ===========================================================================
-- 1 · A NAME IS SEARCHABLE UNTIL ITS OWNER SAYS OTHERWISE
-- ===========================================================================
-- People are found by callsign OR real name. But "Go by callsign" already
-- exists as a preference — user_prefs.identity_display, 'real' | 'username' —
-- and when somebody has chosen it, their real name is not merely hidden from
-- the result, it is NOT MATCHED AT ALL. Searching their real name finds
-- nothing, which is the only version of that promise worth making: a name that
-- is unmatchable cannot be confirmed by guessing it.
--
-- And the function never RETURNS the real name of somebody who goes by
-- callsign. Filtering it in the client would leave it in the response, which is
-- the same leak with a curtain over it.
alter table pilot_profiles add column if not exists real_name text;

/* DROPPED AND RECREATED, not replaced. The signature changes — it returned
   `callsign` and now returns `display_name`, because what a searcher may see is
   no longer always the same string — and Postgres will not let a replace change
   a return type. Dropping a function is not data loss; the guard on the SQL
   runner treats every drop the same and this one needs saying out loud. */
drop function if exists people_search(text, text);

create function people_search(p_me text, p_q text)
returns table (user_id text, display_name text, module_code text, shares_squadron boolean)
language sql
stable
as $$
  with me_prefs as (select p_me as uid)
  select
    p.user_id,
    /* What the searcher is allowed to see them as. Never coalesce to real_name
       for somebody who goes by callsign — that is the leak. */
    case when coalesce(up.identity_display, 'real') = 'username'
         then p.callsign
         else coalesce(p.real_name, p.callsign) end as display_name,
    (select c.module_code from chapter_completions c
      where c.user_id = p.user_id order by c.completed_at desc limit 1) as module_code,
    exists (
      select 1 from squadron_members a
      join squadron_members b on b.squadron_id = a.squadron_id
      where a.user_id = p_me and b.user_id = p.user_id
    ) as shares_squadron
  from pilot_profiles p
  left join user_prefs up on up.user_id = p.user_id
  cross join me_prefs
  where p.discoverable
    and in_my_orbit(p_me, p.user_id)
    and not exists (select 1 from blocks b
                    where (b.user_id = p_me and b.blocked_id = p.user_id)
                       or (b.user_id = p.user_id and b.blocked_id = p_me))
    and coalesce(btrim(p_q), '') <> ''
    and (
      p.callsign ilike '%' || btrim(p_q) || '%'
      /* The real name is matchable ONLY while they have not chosen otherwise. */
      or (coalesce(up.identity_display, 'real') <> 'username'
          and p.real_name ilike '%' || btrim(p_q) || '%')
    )
  order by shares_squadron desc, display_name
  limit 20;
$$;

-- ===========================================================================
-- 2 · SUGGESTIONS — ranked, with the reason attached
-- ===========================================================================
-- Modelled on what a suggestion feed actually does: score on overlap, order by
-- score, and say WHY. A list of rooms in creation order is a directory; the
-- same rooms ordered by how much they have to do with you, each carrying the
-- one fact that earned it its place, is a suggestion.
--
-- WHAT IT MAY NOT DO. It cannot suggest a person outside the orbit. A feed that
-- surfaces strangers is a directory with a ranking function in front of it, and
-- §3 forbids the directory however it is sorted. Squadrons are unrestricted —
-- that is the point of them, and it is why the room is the recommended door and
-- the person is what is behind it.
--
-- The weights are stated as numbers rather than buried in a case expression so
-- they can be argued with. In order of how much they say about whether you
-- belong somewhere: the module you study, then people you already know, then
-- the exam you are sitting, then how alive the room is.

create or replace function suggest_squadrons(p_me text, p_limit integer default 12)
returns table (
  id uuid, name text, blurb text, module_code text, exam_window text,
  join_policy text, members integer, active_week integer, is_full boolean,
  known_ids text[], score integer, reason text
)
language sql
stable
as $$
  with mine as (select squadron_id from squadron_members where user_id = p_me),
  my_mods as (select * from my_modules(p_me)),
  my_exam as (select exam_window e from pilot_profiles where user_id = p_me),
  active as (
    select m.squadron_id, count(distinct pr.user_id)::int n
    from squadron_members m
    left join presence pr on pr.user_id = m.user_id and pr.last_seen > now() - interval '7 days'
    group by m.squadron_id
  ),
  scored as (
    select s.*,
      coalesce(a.n, 0) as active_week,
      squadron_headcount(s.id) as members,
      coalesce(squadron_is_full(s.id), false) as full_now,
      coalesce((select array_agg(sm.user_id) from squadron_members sm
                where sm.squadron_id = s.id and in_my_orbit(p_me, sm.user_id)), '{}') as known,
      (s.module_code in (select * from my_mods))                            as mod_hit,
      (s.exam_window is not null
        and s.exam_window = (select e from my_exam))                        as exam_hit,
      (select count(*) from squadron_members sm
        where sm.squadron_id = s.id and in_my_orbit(p_me, sm.user_id))::int as known_n
    from squadrons s
    left join active a on a.squadron_id = s.id
    where s.join_policy in ('open', 'request')
      and s.id not in (select squadron_id from mine)
      /* Never suggest a room where somebody has blocked you, or you them. */
      and not exists (
        select 1 from squadron_members m
        join blocks b on (b.user_id = p_me and b.blocked_id = m.user_id)
                      or (b.user_id = m.user_id and b.blocked_id = p_me)
        where m.squadron_id = s.id)
  )
  select id, name, blurb, module_code, exam_window, join_policy,
    members, active_week, full_now as is_full, known,
    (   case when mod_hit  then 40 else 0 end
      + case when exam_hit then 20 else 0 end
      + least(known_n * 8, 24)
      + least(active_week, 10) * 2
      + case when full_now then -35 else 0 end
    )::int as score,
    /* ONE REASON, THE STRONGEST. Three reasons on a card is a specification;
       one is a suggestion. Ordered by what actually persuades somebody to join:
       who is already in there beats what it is about. */
    case
      when known_n > 0    then 'known'
      when mod_hit        then 'module'
      when exam_hit       then 'exam'
      when active_week > 0 then 'busy'
      else 'open'
    end as reason
  from scored
  order by score desc, active_week desc, members desc
  limit greatest(1, p_limit);
$$;

-- People, and only ever from inside the orbit. Ranked on the things that
-- predict whether two students are useful to each other: rooms in common,
-- the module they are both in, the sitting they are both working toward, and
-- whether they are awake at the same time.
create or replace function suggest_people(p_me text, p_limit integer default 8)
returns table (
  user_id text, display_name text, module_code text,
  shared_squadrons integer, score integer, reason text
)
language sql
stable
as $$
  with me as (
    select p.exam_window, p.active_window
    from pilot_profiles p where p.user_id = p_me
  ),
  cand as (
    select p.user_id, p.callsign, p.real_name, p.exam_window, p.active_window,
      coalesce(up.identity_display, 'real') as ident,
      (select count(*) from squadron_members a
        join squadron_members b on b.squadron_id = a.squadron_id
        where a.user_id = p_me and b.user_id = p.user_id)::int as shared_sq,
      (select count(*) from lesson_threads t
        where t.author_id = p.user_id and t.module_id in (select * from my_modules(p_me)))::int as posts_here,
      (select max(pr.last_seen) from presence pr where pr.user_id = p.user_id) as seen
    from pilot_profiles p
    left join user_prefs up on up.user_id = p.user_id
    where p.discoverable
      and in_my_orbit(p_me, p.user_id)
      and not exists (select 1 from blocks b
                      where (b.user_id = p_me and b.blocked_id = p.user_id)
                         or (b.user_id = p.user_id and b.blocked_id = p_me))
  )
  select c.user_id,
    case when c.ident = 'username' then c.callsign
         else coalesce(c.real_name, c.callsign) end as display_name,
    (select ch.module_code from chapter_completions ch
      where ch.user_id = c.user_id order by ch.completed_at desc limit 1) as module_code,
    c.shared_sq as shared_squadrons,
    (   least(c.shared_sq * 25, 50)
      + least(c.posts_here * 6, 18)
      + case when c.exam_window is not null
              and c.exam_window = (select exam_window from me) then 15 else 0 end
      + case when c.active_window is not null
              and c.active_window = (select active_window from me) then 10 else 0 end
      + case when c.seen > now() - interval '7 days' then 8 else 0 end
    )::int as score,
    case
      when c.shared_sq > 0 then 'squadron'
      when c.posts_here > 0 then 'answers'
      when c.exam_window = (select exam_window from me) then 'exam'
      when c.active_window = (select active_window from me) then 'hours'
      else 'module'
    end as reason
  from cand c
  order by score desc, c.seen desc nulls last
  limit greatest(1, p_limit);
$$;


-- ############################################################################
-- 0013_retire_pilot_livery.sql
-- ############################################################################

-- 0013 — retire the pilot livery.
--
-- WHAT THIS REMOVES, AND WHY IT IS NOT THE LIVERY YOU ARE THINKING OF.
--
-- Two different things in this codebase were called a livery, and they had
-- nothing to do with each other beyond the word:
--
--   1. The APP's livery — sky / amber / tarmac / beacon / runway / skydrol.
--      Chosen in Profile -> Appearance, written to documentElement as
--      data-livery, and generated by src/lib/liveryEngine.js. This one is
--      current, it is the design system, and 0013 does not touch it.
--
--   2. The PILOT's livery — dawn-patrol / night-ops / contrail / carrier-deck
--      / altimeter / aurora. Picked once during signup, stored here, and used
--      to tint a person's tail. This is the older build's, and it is what 0013
--      removes.
--
-- It had already stopped meaning anything. Every --tail-<id> token in app.css
-- resolved to var(--active) for all twelve ids in both sets, under a comment
-- reading "A person carries no colour of their own under this system" — so the
-- choice painted nothing, on any screen, for anybody. What was left of it was a
-- step in onboarding asking a new student to pick between six swatches that all
-- produce the same colour, before they had seen the product.
--
-- Live values at the time of writing: 3 profiles across 2 distinct liveries,
-- 1 squadron. No information is lost, because none of it was ever rendered.
--
-- Order matters. squadron_roster is language sql and so has a hard catalogue
-- dependency on pilot_profiles.livery: the column cannot be dropped while the
-- function still selects it. Both functions are replaced first, then the
-- columns go.

-- ---------------------------------------------------------------- functions

-- Body copied from the live definition (pg_get_functiondef), with the livery
-- column removed from the one insert that set it. Nothing else changed.
create or replace function assign_squadron(uid text, mod text, stime text)
returns uuid
language plpgsql
as $$
declare target uuid;
begin
  select s.id into target
    from squadron_members m join squadrons s on s.id = m.squadron_id
   where m.user_id = uid and s.module_code = mod
   limit 1;
  if target is not null then return target; end if;

  select s.id into target from squadrons s
   where s.module_code = mod and s.study_time is not distinct from stime
     and (select count(*) from squadron_members m where m.squadron_id = s.id) < 20
   order by (select count(*) from squadron_members m where m.squadron_id = s.id) desc
   limit 1;

  if target is null then
    select s.id into target from squadrons s
     where s.module_code = mod
       and (select count(*) from squadron_members m where m.squadron_id = s.id) < 20
     order by (select count(*) from squadron_members m where m.squadron_id = s.id) desc
     limit 1;
  end if;

  if target is null then
    select s.id into target from squadrons s
     where s.study_time is not distinct from stime
       and (select count(*) from squadron_members m where m.squadron_id = s.id) < 20
     order by (select count(*) from squadron_members m where m.squadron_id = s.id) desc
     limit 1;
  end if;

  if target is null then
    select s.id into target from squadrons s
     where (select count(*) from squadron_members m where m.squadron_id = s.id) < 20
     order by (select count(*) from squadron_members m where m.squadron_id = s.id) desc
     limit 1;
  end if;

  -- none exists yet: open one. It will be 'forming' until it reaches 10.
  if target is null then
    insert into squadrons (module_code, study_time)
    values (mod, stime)
    returning id into target;
  end if;

  insert into squadron_members (squadron_id, user_id)
  values (target, uid)
  on conflict do nothing;

  update squadrons
     set status = case
       when (select count(*) from squadron_members m where m.squadron_id = target) >= 10
       then 'active' else 'forming' end
   where id = target;

  return target;
end $$;

-- The return type loses a column, so create or replace is not enough — the
-- signature has to be dropped first. Nothing in the client reads the result of
-- this one today, so the narrower shape breaks no caller.
drop function if exists squadron_roster(text, uuid);

create function squadron_roster(uid text, sid uuid)
returns table (user_id text, callsign text, marking text, is_staff boolean, joined_at timestamptz)
language sql
stable
as $$
  select m.user_id, p.callsign, m.marking,
         coalesce(p.is_staff, false), m.joined_at
    from squadron_members m
    left join pilot_profiles p on p.user_id = m.user_id
   where m.squadron_id = sid
     and m.user_id not in (select blocked_id from blocks where blocks.user_id = uid)
     and m.user_id not in (select b.user_id from blocks b where b.blocked_id = uid)
   order by m.joined_at;
$$;

-- ------------------------------------------------------------------ columns

alter table pilot_profiles drop column if exists livery;
alter table squadrons      drop column if exists livery;
